name: Create Infrastructure EKS (Kubernetes)

on:
  workflow_dispatch:

jobs:

  terraform-apply-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MEL }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MEL }}
          aws-region: us-east-1

      - name: Setup Kubectl
        uses: Azure/setup-kubectl@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - run: terraform -chdir="./env/dev" init

      - run: terraform -chdir="./env/dev" apply -auto-approve

      - name: Configure kubeconfig with cluster aws
        run: |
          echo "Configuring EKS cluster"
          aws eks update-kubeconfig --name fiap-app-eks --region us-east-1
        if: success()

      - name: Configuring Infra Kubernetes
        run: |
          kubectl apply -f ./kubernetes/api/load-balancer-service.yaml
          kubectl apply -f ./kubernetes/config/db.yaml
          kubectl apply -f ./kubernetes/config/db-migration.yaml
          kubectl apply -f ./kubernetes/db/pod.yaml
          kubectl apply -f ./kubernetes/db/service.yaml
          kubectl apply -f ./kubernetes/api/service.yaml
        env:
          MYSQL_ROOT_USERNAME: '${{ secrets.MYSQL_ROOT_USERNAME }}'
          MYSQL_ROOT_PASSWORD: '${{ secrets.MYSQL_ROOT_PASSWORD }}'
          MERCADO_PAGO_USER_ID: '${{ secrets.MERCADO_PAGO_USER_ID }}'
          MERCADO_PAGO_EXTERNAL_ID: '${{ secrets.MERCADO_PAGO_EXTERNAL_ID }}'
          MERCADO_PAGO_TOKEN: '${{ secrets.MERCADO_PAGO_TOKEN }}'
          MERCADO_PAGO_WEBHOOK_URL: '${{ secrets.MERCADO_PAGO_WEBHOOK_URL }}'
        if: success()

      - name: Test connection
        run: kubectl get svc
        if: success()